config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      match 'boomerangs/get_records', controller: 'boomerangs', :via => :get, defaults: {format: :json}
    end
  end

  resources :boomerangs, except: [:destroy, :show]
  match 'boomerangs/boompost' => 'boomerangs#boompost', :via => [:get, :post]
  match 'mystatus' => 'boomerangs#mystatus', :via => :get
  match 'stats' => 'boomerangs#stats', :via => :get, :as => 'stats'
  match 'boomerangs/viahost_setup' => 'boomerangs#viahost_setup', :via => :get

  root 'boomerangs#stats'

end

app/models/boomerang.rb
class Boomerang < ActiveRecord::Base

  # boomerang attributes
  BOOMERANG_COLUMNS = [
      :host,
      :bw,
      :bw_err,
      :bw_time,
      :lat,
      :lat_err,
      :clientip,
      :method,
      :nt_con_end,
      :nt_con_st,
      :nt_dns_end,
      :nt_dns_st,
      :nt_domcomp,
      :nt_domcontloaded_end,
      :nt_domcontloaded_st,
      :nt_domint,
      :nt_domloading,
      :nt_fet_st,
      :nt_load_end,
      :nt_load_st,
      :nt_nav_st,
      :nt_nav_type,
      :nt_red_cnt,
      :nt_red_end,
      :nt_red_st,
      :nt_req_st,
      :nt_res_end,
      :nt_res_st,
      :nt_unload_end,
      :nt_unload_st,
      :referer,
      :req_time,
      :rt_bstart,
      :rt_end,
      :rt_start,
      :rt_tstart,
      :user,
      :useragent,
      :http_ver,
      :location,
      :status,
      :t_done,
      :t_page,
      :t_resp,
      :uri_path,
      :version
  ]

  # return average / default of last 4 hours
  def self.avg_beacon(beacon,metric,hrs=4)
    if Boomerang.exists?(:host => beacon)
      Boomerang.where(created_at: (DateTime.now - hrs.hours)..DateTime.now).where(host: beacon).average(metric.to_sym)
    end
  end

end

app/controllers/api/v1/boomerangs_controller.rb
class Api::V1::BoomerangsController < Api::ApiBaseController

  after_filter only: [:index] { set_pagination_header(:boomerangs) }

  def show
  end

  def get_records
    total = Boomerang.count
    first_possible = Boomerang.first.id
    last_possible = Boomerang.last.id
    limit = 10000
    last = total
    first = total - 1000
    range = params[:range] ||= first..last
    to_num = "#{range}".split('..').map{|d| Integer(d)}
    range = to_num[0]..to_num[1]
    @boomerangs = Boomerang.where(:id => range)
    date_range = "#{@boomerangs.first.created_at.to_i}..#{@boomerangs.last.created_at.to_i}"
    respond_to do |format|
      if range.count > limit
        format.json { render :json => { :status => "error", :message => "Range #{range} with a count of #{range.count} is over the limit of #{limit} per query"} }
      else
        format.json { render :json => { :status => "ok", :info => {:total_records => total, :range_available => first_possible..last_possible, :request_limit => limit, :current_count => range.count, :current_range => range, :current_date_range => date_range}, :records => @boomerangs} }
      end
    end
  end

end

app/controllers/boomerangs_controller.rb
class BoomerangsController < ApplicationController

  def mystatus
    @start_range = (Time.now - 14400).strftime("%b%d %l:%M%P")
    @end_range = (Time.now).strftime("%b%d %l:%M%P")
    @beacon = APP_CONFIG['beacon_host']
    if Boomerang.exists?(:host => @beacon)
      @viahostabw = (Boomerang.avg_beacon(@beacon,'bw') or 0).round(2)
      @viahostalat = (Boomerang.avg_beacon(@beacon,'lat') or 0).round(2)
      @viahostabw = ((@viahostabw or 0) * 8 / 1024 / 1024).round(2)
    end
  end

  def stats
    beacon = APP_CONFIG['beacon_host']
    if params[:start_date].present?
      tstart = DateTime.strptime(params[:start_date], '%m-%d-%Y %H:%M').change(:offset => "-0400")
      tend = DateTime.strptime(params[:start_date], '%m-%d-%Y %H:%M').change(:offset => "-0400") + params[:plus_hours].to_i.hours
    else
      tstart = Time.now - 8.hours
      tend = Time.now
    end
    @bandwidth = Boomerang.where('host=? and bw>?', beacon, 0).group_by_hour(:req_time, format: "%l%P",range: tstart..tend).average(:bw)
    @bandwidth.each { |k, v| @bandwidth[k] = (v * 8 / 1024 / 1024).round(2)}
    @nwlatency = Boomerang.where(host: beacon).group_by_hour(:req_time, format: "%l%P",range: tstart..tend).average(:lat)
  end

  # set attributes for javascript via gon gem
  def viahost_setup
    gon.requestip = request.remote_ip
    gon.base = request.base_url
    $RESOURCE_LOGGER.info "base_url = #{request.base_url}, request_host = #{request.host}"
    gon.useragent = request.user_agent
    gon.rmethod = request.method
    gon.req_time = Time.now.to_i
    gon.uri_path = request.filtered_path
    gon.host = request.host
    gon.viahostbw = ((Boomerang.avg_beacon(APP_CONFIG['beacon_host'],'bw') or 0) * 8 / 1024 / 1024).round(2)
    gon.viahostlat = (Boomerang.avg_beacon(APP_CONFIG['beacon_host'],'lat') or 0).round(2)
    render layout: 'viahost'
  end

  def index
    if params[:query].present?
      if params[:start_date].present? and params[:end_date].present?
        $RESOURCE_LOGGER.info "s = #{params[:start_date]}, e = #{params[:end_date]}"
        sdate = DateTime.strptime(params[:start_date], '%m-%d-%Y %H:%M').change(:offset => "-0400")
        edate = DateTime.strptime(params[:end_date], '%m-%d-%Y %H:%M').change(:offset => "-0400")
        $RESOURCE_LOGGER.info "s = #{sdate}, e = #{edate}"
        @boomerangs = Boomerang.where(:created_at => sdate..edate).where("host like ? or clientip like ?", "%#{params[:query]}%", "%#{params[:query]}%").reverse_order.paginate(:page => params[:page])
      else
        # @boomerangs = Boomerang.all.reverse_order.paginate(:page => params[:page])
        @boomerangs = Boomerang.where("host like ? or clientip like ?", "%#{params[:query]}%", "%#{params[:query]}%").reverse_order.paginate(:page => params[:page])
      end
    else
      if params[:start_date].present? and params[:end_date].present?
        $RESOURCE_LOGGER.info "s = #{params[:start_date]}, e = #{params[:end_date]}"
        sdate = DateTime.strptime(params[:start_date], '%m-%d-%Y %H:%M').change(:offset => "-0400")
        edate = DateTime.strptime(params[:end_date], '%m-%d-%Y %H:%M').change(:offset => "-0400")
        $RESOURCE_LOGGER.info "s = #{sdate}, e = #{edate}"
        @boomerangs = Boomerang.where(:created_at => sdate..edate).paginate(:page => params[:page])
      else
        @boomerangs = Boomerang.all.reverse_order.paginate(:page => params[:page])
      end
    end
  end

  def show
  end

  def new
    @boomerang = Boomerang.new
  end

  def edit
  end

  def boompost
    if params['t_page'].nil?
      render :text => ""
      return
    end
    # rename input names to match column names
    replacements = { "rt.start" => "rt_start", "rt.bstart" => "rt_bstart", "rt.end" => "rt_end", "rt.start" => "rt_start", "r" => "referer" }
    replacements.each do |k, v|
      params[v] = params.delete(k)
    end
    ## filter out params we don't need/use
    # permitted params
    columns = Boomerang::BOOMERANG_COLUMNS
    columns = columns.map { |x| x.to_s }
    # filter params, keep only the ones we care about
    filtered = params.slice(*columns).to_hash
    # convert time to epoch
    filtered['req_time'] = Time.at(filtered['req_time'].to_i)
    Boomerang.new(filtered).save
    render :text => ""
  end

  def create
  end

  def update
    respond_to do |format|
      if @boomerang.update(boomerang_params)
        format.html { redirect_to @boomerang, notice: 'Boomerang was successfully updated.' }
        format.json { render :show, status: :ok, location: @boomerang }
      else
        format.html { render :edit }
        format.json { render json: @boomerang.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @boomerang.destroy
    respond_to do |format|
      format.html { redirect_to boomerangs_url, notice: 'Boomerang was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_boomerang
    @boomerang = Boomerang.find(params[:id])
    logger.debug "Getting boomerang: #{@boomerang.inspect}"
  end

  def boomerang_params
    fields = Boomerang::BOOMERANG_COLUMNS
    params.require(:boomerang).permit(*fields)
  end

end

app/helpers/boomerangs_helper.rb
module BoomerangsHelper
end

app/views/boomerangs/index.html.slim
= form_tag boomerangs_path, method: :get do
  div style="float:left;"
  div class="container"
    div class='col-md-3'
      div class="form-group"
        = label_tag :start_date, 'Start Date'
        div class='input-group date' id='datetimepicker6'
          = text_field_tag :start_date, params[:start_date], class: 'form-control', data: {date_format: 'MM-DD-YYYY HH:00'}, :include_blank => true
          span class="input-group-addon"
            span class="glyphicon glyphicon-calendar"
    div class='col-md-3'
      div class="form-group"
        = label_tag :end_date, 'End Date'
        div class='input-group date' id='datetimepicker7'
          = text_field_tag :end_date, params[:end_date], class: 'form-control', data: {date_format: 'MM-DD-YYYY HH:00'}, :include_blank => true
          span class="input-group-addon"
            span class="glyphicon glyphicon-calendar"
    div class='col-md-3'
      div class='form-group'
        = label_tag :query, 'Search Term'
        div class="input-group"
          = text_field_tag :query, params[:query], class: 'form-control', autocomplete: 'off', :include_blank => true
    div class='col-md-2'
      div class="form-group"
        = label_tag :bogus, '.', :style => 'color:#FFFFFF;'
        div class='input-group'
          = submit_tag("Submit", :class => "btn btn-primary btn-sm")
          - if params[:start_date].present? && params[:end_date].present?
            = link_to "Clear", boomerangs_path, class: "btn btn-secondary btn-sm"
    br
h2 Transactions

.viapagination
  = will_paginate (@boomerangs)

table class="table table-striped table-hover" width="100%"
  thead
    tr
      th Client IP
      th Beacon
      th Latency (ms)
      th Bandwidth (mbps)
      th Request Time
  tbody
    - @boomerangs.each do |boomerang|
      tr
        td = boomerang.clientip
        td = boomerang.host
        td = boomerang.lat
        td = (boomerang.bw * 8.0 / 1024.0 / 1024.0).round(2)
        td = boomerang.req_time

app/views/boomerangs/mystatus.html.slim
h2 This Server
p style="font-size: 15px;"
  em
    | user averages: bandwidth #{@viahostabw} mbps, latency #{@viahostalat} ms - [#{@start_range} - #{@end_range}]
iframe src="/boomerangs/viahost_setup" width="600" height="225" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"
div style="margin-left: 45px;"
  i larger bandwidth is better, smaller latency is better
br

app/views/boomerangs/stats.html.slim
/h2 Client Statistics
/br
= form_tag stats_path, method: :get do
  div class="container"
    div class='col-md-3'
      div class="form-group"
        = label_tag :start_date, 'Start Date/Hour'
        div class='input-group date' id='datetimepicker6'
          = text_field_tag :start_date, params[:start_date], class: 'form-control', data: { date_format: 'MM-DD-YYYY HH:00' }, :include_blank => true
          span class="input-group-addon"
            span class="glyphicon glyphicon-calendar"
    div class='col-md-1'
      div class="form-group"
        = label_tag :plus_hours, 'Hours(+)'
        div class='input-group'
          = select_tag :plus_hours, options_for_select((1..8), params[:plus_hours]), class: "form-control", :include_blank => true
    div class='col-md-3'
      div class="form-group"
        = label_tag :bogus, '.', :style => 'color:#FFFFFF;'
        div class='input-group'
          = submit_tag("Submit", :class => "btn btn-primary btn-sm")
          - if params[:start_date].present? or params[:plus_hours].present?
            = link_to "Clear", stats_path, class: "btn btn-secondary btn-sm"
h2 Network Stats
br
br

h4 Via Host - Network Bandwidth (avg/mbps)
= column_chart @bandwidth, height: "200px"
h4 Via Host - Network Latency (avg/ms)
= column_chart @nwlatency, height: "200px"